In [2]:
import xarray as xr
import numpy as np

In [3]:
data_directory = r"/oscar/home/pvankatw/data/pvankatw/CMIP/"
data_path = r"pr_day_MPI-ESM1-2-HR_ssp585_r1i1p1f1_gn_20150101-20191231.nc"

ds = xr.open_dataset(data_directory + data_path)
ds


<xarray.Dataset> Size: 539MB
Dimensions:    (time: 1826, bnds: 2, lat: 192, lon: 384)
Coordinates:
  * time       (time) datetime64[ns] 15kB 2015-01-01T12:00:00 ... 2019-12-31T...
  * lat        (lat) float64 2kB -89.28 -88.36 -87.42 ... 87.42 88.36 89.28
  * lon        (lon) float64 3kB 0.0 0.9375 1.875 2.812 ... 357.2 358.1 359.1
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] 29kB ...
    lat_bnds   (lat, bnds) float64 3kB ...
    lon_bnds   (lon, bnds) float64 6kB ...
    pr         (time, lat, lon) float32 539MB ...
Attributes: (12/47)
    Conventions:            CF-1.7 CMIP-6.2
    activity_id:            ScenarioMIP
    branch_method:          standard
    branch_time_in_child:   60265.0
    branch_time_in_parent:  60265.0
    contact:                cmip6-mpi-esm@dkrz.de
    ...                     ...
    title:                  MPI-ESM1-2-HR output prepared for CMIP6
    variable_id:            pr
    variant_label:          r1i1p1f1
    license:                CMIP6 model data produced by DKRZ is licensed und...
    cmor_version:           3.4.0
    tracking_id:            hdl:21.14100/9093c676-cbb8-4c96-a25b-3a68ed8606f0

In [4]:
grid_directory = r"/oscar/home/pvankatw/data/pvankatw/pvankatw-bfoxkemp/Grid_Files/"
ais_grids = "AIS_sectors_8km.nc"
grids = xr.open_dataset(grid_directory + ais_grids)
grids


<xarray.Dataset> Size: 9MB
Dimensions:  (y: 761, x: 761)
Coordinates:
    lon      (y, x) float32 2MB ...
    lat      (y, x) float32 2MB ...
  * x        (x) float32 3kB -3.04e+06 -3.032e+06 ... 3.032e+06 3.04e+06
  * y        (y) float32 3kB -3.04e+06 -3.032e+06 ... 3.032e+06 3.04e+06
Data variables:
    sectors  (y, x) float32 2MB ...
    regions  (y, x) float32 2MB ...
    mapping  |S1 1B ...
Attributes:
    Author:    Helene Seroussi (helene.seroussi@jpl.nasa.gov)
    Project:   ISMIP6 Antarctica
    Variable:  Sectors experiment
    Grid:      Datum = WGS84, earth_radius = 6378137., earth_eccentricity = 0...
    proj:      +proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0...
    proj4:     +init=epsg:3031
    Date:      11-Oct-2019

In [5]:
import xesmf as xe
regridder = xe.Regridder(ds, grids, 'bilinear')
regridder

xESMF Regridder 
Regridding algorithm:       bilinear 
Weight filename:            bilinear_192x384_761x761.nc 
Reuse pre-computed weights? False 
Input grid shape:           (192, 384) 
Output grid shape:          (761, 761) 
Periodic in longitude?      False

In [6]:
ds_regridded = regridder(ds["pr"])

In [7]:
ds_regridded

<xarray.DataArray (time: 1826, y: 761, x: 761)> Size: 4GB
array([[[6.4534906e-05, 6.5739252e-05, 6.7255765e-05, ...,
         3.4622441e-05, 3.4447465e-05, 3.3935325e-05],
        [6.2255094e-05, 6.3669358e-05, 6.5185901e-05, ...,
         3.3039356e-05, 3.2865533e-05, 3.3027623e-05],
        [6.0260019e-05, 6.1674094e-05, 6.3091131e-05, ...,
         3.1549414e-05, 3.1790827e-05, 3.1952644e-05],
        ...,
        [1.5263900e-05, 1.4455120e-05, 1.3683498e-05, ...,
         5.3621457e-05, 5.2323168e-05, 5.1052317e-05],
        [1.4524882e-05, 1.3716421e-05, 1.3430584e-05, ...,
         5.3914719e-05, 5.2791987e-05, 5.1521158e-05],
        [1.3791166e-05, 1.3457687e-05, 1.3171810e-05, ...,
         5.4166849e-05, 5.3044696e-05, 5.2167859e-05]],

       [[8.5016378e-05, 8.4404950e-05, 8.3531413e-05, ...,
         4.0840911e-05, 4.2506595e-05, 4.2830994e-05],
        [8.6616870e-05, 8.5877684e-05, 8.5004169e-05, ...,
         4.0296112e-05, 4.1961768e-05, 4.2551663e-05],
        [8.7943699e-05, 8.7204426e-05, 8.6496548e-05, ...,
         3.9666691e-05, 4.0325544e-05, 4.0915540e-05],
...
        [1.5631786e-05, 1.7264769e-05, 1.8853796e-05, ...,
         2.0251525e-04, 1.9912177e-04, 1.9576060e-04],
        [1.4381356e-05, 1.6013146e-05, 1.7403783e-05, ...,
         2.0822536e-04, 2.0612522e-04, 2.0276273e-04],
        [1.4391948e-05, 1.4600264e-05, 1.5990372e-05, ...,
         2.1392808e-04, 2.1182692e-04, 2.0959513e-04]],

       [[6.9266076e-07, 5.1018242e-07, 6.4101022e-07, ...,
         3.1057039e-05, 3.0004961e-05, 2.9320676e-05],
        [4.5080654e-07, 5.8908176e-07, 7.1989382e-07, ...,
         2.9257817e-05, 2.8206106e-05, 2.8018094e-05],
        [5.3465146e-07, 6.7301488e-07, 8.0846559e-07, ...,
         2.7476728e-05, 2.7339358e-05, 2.7151138e-05],
        ...,
        [1.5495740e-05, 1.6136324e-05, 1.6839229e-05, ...,
         1.7603212e-05, 1.8525507e-05, 1.9450670e-05],
        [1.5239910e-05, 1.5880727e-05, 1.7489059e-05, ...,
         1.5556998e-05, 1.5299609e-05, 1.6225416e-05],
        [1.5420332e-05, 1.6556101e-05, 1.8164366e-05, ...,
         1.3608107e-05, 1.3350593e-05, 1.3696729e-05]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 15kB 2015-01-01T12:00:00 ... 2019-12-31T12...
    lon      (y, x) float32 2MB -135.0 -135.1 -135.2 -135.2 ... 44.85 44.92 45.0
    lat      (y, x) float32 2MB -51.85 -51.9 -51.94 ... -51.94 -51.9 -51.85
  * x        (x) float32 3kB -3.04e+06 -3.032e+06 ... 3.032e+06 3.04e+06
  * y        (y) float32 3kB -3.04e+06 -3.032e+06 ... 3.032e+06 3.04e+06
    mapping  |S1 1B ...
Attributes:
    regrid_method:  bilinear

In [8]:
ds_regridded.to_netcdf("bilinear.nc")

In [4]:
lat_b = np.concatenate(([ds.lat_bnds.values[0,0]], ds.lat_bnds.values[:,1]))
lon_b = np.concatenate(([ds.lon_bnds.values[0,0]], ds.lon_bnds.values[:,1]))

In [16]:
source = xr.Dataset(
    {
        "pr": (["time", "lat", "lon"], ds["pr"].values),
        "lat": (["lat"], ds["lat"].values),
        "lon": (["lon"], ds["lon"].values),
        "lat_b": (["lat_b"], lat_b),
        "lon_b": (["lon_b"], lon_b),
    }
)

source

<xarray.Dataset> Size: 539MB
Dimensions:  (time: 1826, lat: 192, lon: 384, lat_b: 193, lon_b: 385)
Coordinates:
  * lat      (lat) float64 2kB -89.28 -88.36 -87.42 -86.49 ... 87.42 88.36 89.28
  * lon      (lon) float64 3kB 0.0 0.9375 1.875 2.812 ... 357.2 358.1 359.1
  * lat_b    (lat_b) float64 2kB -89.75 -88.82 -87.89 ... 87.89 88.82 89.75
  * lon_b    (lon_b) float64 3kB -0.4688 0.4688 1.406 ... 357.7 358.6 359.5
Dimensions without coordinates: time
Data variables:
    pr       (time, lat, lon) float32 539MB 2.249e-06 2.39e-06 ... 1.206e-06

In [21]:
source.pr.shape

(1826, 192, 384)

In [22]:
import cf_xarray as cfxr

In [ ]:
# Get the bounds variable and convert them to "vertices" format
# Order=none, means that we do not know if the bounds are listed clockwise or counterclockwise, so we ask cf_xarray to try both.
lat_corners = cfxr.bounds_to_vertices(ds_in.vertices_latitude, "vertices", order=None)
lon_corners = cfxr.bounds_to_vertices(ds_in.vertices_longitude, "vertices", order=None)
ds_in_crns = ds_in.assign(lon_b=lon_corners, lat_b=lat_corners)

In [4]:
data_path = r"/oscar/home/pvankatw/data/pvankatw/pvankatw-bfoxkemp/GHub-ISMIP6-Forcing/AIS/Atmosphere_Forcing/ccsm4_rcp2.6/Regridded_8km/CCSM4_8km_anomaly_rcp26_1995-2100.nc"

ds = xr.open_dataset(data_path)
ds


<xarray.Dataset> Size: 1GB
Dimensions:          (time: 106, y: 761, x: 761, nv4: 4)
Coordinates:
  * time             (time) object 848B 1995-01-16 12:00:00 ... 2100-01-16 12...
    lon              (y, x) float64 5MB ...
    lat              (y, x) float64 5MB ...
Dimensions without coordinates: y, x, nv4
Data variables:
    lon_bnds         (y, x, nv4) float64 19MB ...
    lat_bnds         (y, x, nv4) float64 19MB ...
    pr_anomaly       (time, y, x) float32 246MB ...
    evspsbl_anomaly  (time, y, x) float32 246MB ...
    mrro_anomaly     (time, y, x) float32 246MB ...
    smb_anomaly      (time, y, x) float32 246MB ...
    ts_anomaly       (time, y, x) float32 246MB ...
    lat2d            (y, x) float64 5MB ...
    lon2d            (y, x) float64 5MB ...
    year             (time) int32 424B ...
Attributes:
    CDI:          Climate Data Interface version 1.9.5 (http://mpimet.mpg.de/...
    Conventions:  CF-1.6
    history:      Tue Feb 19 15:22:07 2019: cdo remapycon,ISM_AN_08km_CDO_fil...
    CDO:          Climate Data Operators version 1.9.5 (http://mpimet.mpg.de/...

In [13]:
target = xr.open_dataset(r"/oscar/home/pvankatw/data/pvankatw/pvankatw-bfoxkemp/GHub-ISMIP6-Forcing/AIS/Atmosphere_Forcing/ccsm4_rcp2.6/Regridded_8km/CCSM4_8km_anomaly_rcp26_1995-2100.nc")


In [14]:
target

<xarray.Dataset> Size: 1GB
Dimensions:          (time: 106, y: 761, x: 761, nv4: 4)
Coordinates:
  * time             (time) object 848B 1995-01-16 12:00:00 ... 2100-01-16 12...
    lon              (y, x) float64 5MB ...
    lat              (y, x) float64 5MB ...
Dimensions without coordinates: y, x, nv4
Data variables:
    lon_bnds         (y, x, nv4) float64 19MB ...
    lat_bnds         (y, x, nv4) float64 19MB ...
    pr_anomaly       (time, y, x) float32 246MB ...
    evspsbl_anomaly  (time, y, x) float32 246MB ...
    mrro_anomaly     (time, y, x) float32 246MB ...
    smb_anomaly      (time, y, x) float32 246MB ...
    ts_anomaly       (time, y, x) float32 246MB ...
    lat2d            (y, x) float64 5MB ...
    lon2d            (y, x) float64 5MB ...
    year             (time) int32 424B ...
Attributes:
    CDI:          Climate Data Interface version 1.9.5 (http://mpimet.mpg.de/...
    Conventions:  CF-1.6
    history:      Tue Feb 19 15:22:07 2019: cdo remapycon,ISM_AN_08km_CDO_fil...
    CDO:          Climate Data Operators version 1.9.5 (http://mpimet.mpg.de/...

In [12]:
target.lat_bnds[0, 0, :].values

array([-51.84954, -51.89626, -51.84954, -51.80288])

In [16]:
gridfile = xr.open_dataset("/users/pvankatw/research/ise/gridfiles/grid_ISMIP7_g1_AIS_08000m.nc")
gridfile

<xarray.Dataset> Size: 47MB
Dimensions:   (y: 761, x: 761, nv4: 4)
Coordinates:
    lat       (y, x) float64 5MB ...
    lon       (y, x) float64 5MB ...
Dimensions without coordinates: y, x, nv4
Data variables:
    lat_bnds  (y, x, nv4) float64 19MB ...
    lon_bnds  (y, x, nv4) float64 19MB ...
    dummy     (y, x) int8 579kB ...

In [25]:
gridfile.lat[0, :5].values

array([-51.84956701, -51.89623242, -51.94284884, -51.98941596,
       -52.03593349])

In [26]:
target.lat[0, :5].values

array([-51.84957, -51.89623, -51.94285, -51.98942, -52.03593])

In [29]:
grids.lat[0, :5].values

array([-51.85032 , -51.896984, -51.9436  , -51.990166, -52.036682],
      dtype=float32)